name: Build & Push Docker (Simple)

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted  # Ton runner Windows

    steps:
      # 1) Récupérer le code
      - uses: actions/checkout@v4

      # 2) Connexion Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3) Build l'image avec Docker CLI classique
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tpm-app:latest .

      # 4) Pousser l'image vers Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tpm-app:latest
